spring.application.name=trello

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/trello
spring.datasource.username=trello
spring.datasource.password=trello
spring.datasource.driver-class-name=org.postgresql.Driver


#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true